### PR TITLE
Implement basic page-related API handlers

### PR DESCRIPTION
**Pull request by loboyd**
This PR implements the following API handlers (all request and response data packets should be of type `application/json`):

* for getting an existing page:
```
GET /api/pages/{id}

request data:
none

response data:
{
  "page": {
    "id": id,
    "title": "some-base64-string",
    "body": "another-base64-string",
    "owner_id": another_id,
  },
  "key": "more-base64"
}
```

* for creating a new page:
```
POST /api/pages/

request  data:
{
  "key": "some-base64-string",
}

response data:
{
  "id": some-id,
}
```

* for updating an existing page:
```
POST /api/pages/{id}

request data:
{
  "page": {
    "title": "some-base64-string",
    "body": "another-base64-string",
  },
}

response data:
none
```

* for deleting an existing page:
```
DELETE /api/pages/{id}

request data:
none

response data:
none
```

### CODE REVIEW

**Comment by bmgxyz** [comment]
Nice work! I appreciate the bootleg documentation. I'm testing out each endpoint by calling the functions in `cmd/static/test.html`, but I get the following error when I run `testCreatePage()`.

```
2019/12/08 17:25:56 Inside the pages handler...
2019/12/08 17:25:56 looking for session token header...
2019/12/08 17:25:56 successfully found bearer token
2019/12/08 17:25:56 checking session token...
2019/12/08 17:25:56 looking for session token in cache...
2019/12/08 17:25:56 successfully got session token from cache
2019/12/08 17:25:56 successfully confirmed authorization
2019/12/08 17:25:56 successfully retrieved user 1
2019/12/08 17:25:56 generating ID for new page...
2019/12/08 17:25:56 creating row in `pages` table...
2019/12/08 17:25:56 failed to create page pq: null value in column "title" violates not-null constraint                               
2019/12/08 17:25:56 failed to generate ID
```

Note that I modified `pkg/storage/postgres/page.go` to return the Postgres error. I get nothing back when I run `select * from pages`, so it seems it really is failing. It looks like it's complaining about the lack of a `title` value, but I can't quite trace it back. Any ideas? Maybe there needs to be a default value set somewhere?

**Comment by loboyd** [comment]
Oh, I'm sorry! I neglected to mention that there are two minor database changes required:
```
ALTER TABLE pages ALTER COLUMN title DROP NOT NULL;
ALTER TABLE pages DROP COLUMN version;

```

**Comment by bmgxyz** [comment]
Commit :clap: your :clap: database :clap: changes. That's why I wrote `manage_db.sh`.

\*grumble\*grumble\*grumble\*

**Comment by loboyd** [comment]
Committed. We should probably make a directory under `/` to store the dumps in rather than just putting them in `/cmd/`. In fact, `manage_db.sh` should probably be under `/` as well.

**Review by bmgxyz — APPROVED** [review]
Overall, I continue to be pleased and impressed by your work. With these four basic functions, which seem to work fine on my machine, I can begin rebuilding the existing frontend with asynchronous API calls. (And I'll have to, since these changes break the site.) I'll begin that process immediately.

A question for the future: is there any error handling in the API? In other words, what happens when I ask for a page that doesn't exist? The JS frontend in `cmd/static/test.html` doesn't seem to indicate anything in particular, but I haven't looked through the backend code to see whether or not you serve up `404`, etc.

Well done. Merge at your convenience.

**Comment by loboyd** [comment]
Thanks for the kind words. I'll go ahead and merge now.

The API should return standard HTTP status code, e.g., `201` is returned when a new page is created. One exception is that `404` is returned for unauthorized access attempt rather than the designated `403` so that we can hide existence of the resource from the unauthorized caller. I have noticed at least one place in my implementation where there is a minor bug though which is that the call you mentioned above (`GET /api/pages/{id}`) attempt returns a `500` instead of `404` (look in the console for this) when the page doesn't exist.

**Pull request merged**
