### PR TITLE
Implement authentication compatible with client-side encryption

### PR DESCRIPTION
**Pull request by loboyd**
setonotes requires a slightly more sophisticated than usual authentication
scheme. This is because a user's password is used for both authentication
**and** encryption/decryption of private material. For this reason, a user's
plaintext password is never to be sent to the server. Instead, the password is
used to generate two separate keys--one for authentication, and the other for
encryption.

This is achieved by the server maintaining both an authentication salt and an
encryption salt for each user. Then, the keys are generated as follows:

```
authentication_key = PBKDF2(password, authentication_salt)
encryption_key     = PBKDF2(password, encryption_salt)
```

The authentication key is used in exactly the same way as a plaintext password
would be used in a typical authentication scheme. It is submitted via a POST
request along with the username over a TLS connection and hashed and salted
with `bcrypt` on the server.

The encryption key is stored on the client, and it never transferred to the
server for any reason.

# New account
To create a new account, the following procedure is executed:
1. Two salts are generated (one for each of encryption and authentication).
2. The client generates both the authentication key and the encryption key.
3. The encryption key is stored on the client.
4. The authentication key is submitted with the username.
5. The server uses the `bcrypt` comparator function against the submitted
   authentication key to provide or deny the client authenticated status.

# Existing account
To authenticate an existing user, the following procedure is executed:
1. The username is submitted to the server.
2. The server responds with both the authentication salt and the encryption salt
   for the given username. Note that salts are cryptographically public
   material.
3. The client generates both the authentication key and the encryption key.
4. The encryption key is stored on the client.
5. The authentication key is submitted (once again with the username).
6. The server uses the `bcrypt` comparator function against the submitted
   authentication key to provide or deny the client authenticated status.

### CODE REVIEW

**Comment by loboyd** [comment]
Sorry for the massive PR. I'll try to not do that in the future.

**Comment by bmgxyz** [comment]
It _is_ quite large, but all necessary. I don't mind reviewing lots of changes if they make `setonotes` better.

I'm going to try to get set up here with the new database schema, and then I'll be able to properly review your changes.

**Review by bmgxyz — CHANGES_REQUESTED** [review]
Impressive work. After you pushed the correct schema, I was able to add a username to the `beta_testers` table and sign up using the web interface. (Both it and the sign in page are visually appealing and a significant improvement; well done.) Logging in and out seem to work fine and happen quickly. The reference page was generated properly and was editable without any trouble. There are some bugs with the editor (notably the inability to change the title of a note), but those are mainly in my domain. I'll fix them in the future.

Just a few changes and thoughts:

- `cmd/static/js/easymde.min.js` should be `git rm`'d. I failed to `.gitignore` this file properly in a previous commit, so even though you've fast-forwarded this branch to include the proper `.gitignore` that I subsequently pushed, the ignored file remains.
- Is `cmd/templates/signin.html.back` just a backup file? If so, it should be `git rm`'d as well.
- When I read in `schema.psql`, I got a few errors complaining about a missing role called `lboyd`. I didn't notice any missing or broken functionality, but it's still a little concerning. Do you have any idea what could cause this? If so, consider addressing it here before merging.

**Comment by loboyd** [comment]
Thank you. I'm glad everything went smoothly once you got the database changes!

1, 2. Ah, right. I didn't think of that, but I will stop tracking those things before I merge.
3. I'm not sure what happened there. I do have a Postgres database set up under the name `lboyd` on my machine, so maybe that's causing some junk to appear in the dump?

**Pull request merged**
