### PR TITLE
Editor Improvements

### PR DESCRIPTION
**Pull request by bmgxyz**
The editor is dead; long live the editor. :tada:

The editor is now in a state that I'll call "usable". There are still _many_ features that I want to implement (including some that I tried to implement for this PR but failed), but it's at least passable now. In other words, I would tolerate this editor if I had no other choice but to use it.

## Notable Changes

- Move editor CSS out of its template and into a dedicated stylesheet (`style.css`)
- Improve the layout and styling of the toolbar, the preview and editor text, and the editor in general
- Make the parser ignore single line breaks so hard-wrapped paragraphs display properly
- Synchronize the scroll of the editor and preview
- Add several keyboard shortcuts (e.g. `a` to launch the editor in addition to `i`, `Backspace` to return to the directory from preview mode, etc.)
- Add math support again (but with a visual bug related to how inline styling is applied between math delimiters)
- Add a title field to the editor so the user can change it
- Highlight the active line in the editor
- Prompt the user if they try to close or navigate away from the editor before saving their changes, if any
- Squash a whole bunch of bugs

## Future Feature Ideas

- Connecting the title field and the editor so the user can use the arrow keys to move freely between them (currently the user has to click the title field to select it)
- If the user switches to preview mode, doesn't scroll, and switches back to the editor, then don't move the cursor (currently it gets moved to where the editor thinks it should go, as if the user had just scrolled there)
- Improve Markdown compliance (footnotes, en/em dashes, ellipses, fixed-width table editing, etc.)
- Auto-launch the editor when the note is empty (read: new)
- Add a "copy to clipboard" button to code blocks
- Find / search
- Printing support
- Import / export
- Night mode
- much, _much_ more

Review and merge at your convenience. Once this and the API are both merged, I'll start integrating them.

### CODE REVIEW

**Comment by loboyd** [comment]
This is really starting to look and feel great. 

**bugs:**
* I get the "Changes you made may not be saved." dialogue when I click the save icon.
* [don't ask how I discovered this] If the current line is just `~~~~~~~~~~~~~~~~~~~~~~~~` and you click the code icon, it deletes the line above it and sometimes just gets stuck deleting another line every time you press it.

**feature ideas**
* Make TAB useful inside the editor.

I'm going to leave this unmerged in case you want to handle one or both of those bugs before merging, but feel free to merge whenever you feel is good.

**Comment by bmgxyz** [comment]
Thank you. I'm proud of the progress I've made, even in spite of the obvious areas that need improvement.

- Yeah, I noticed that too. It looks like a case of lazy coding and testing on my part. I'll try to fix it before merging.
- I couldn't reproduce this, but I at least believe in the idea that the toolbar button functions could have bugs. Maybe you can show me how to trigger this one.

- A good idea. Right now, if you're in a `<ul>` or `<ol>` and hit `Tab`, you'll indent. `Shift+Tab` dedents, as you'd expect. I think `Tab` could be useful for other stuff, but I'm not sure what. Any ideas?

Okay, like I said, I'll take on that save changes bug and then merge.

**Comment by loboyd** [comment]
Sorry, it didn't even occur to me that the usecase I had in mind for TAB was also a special case since most of Markdown has no use for `\t`. But I was thinking `\t` for inside inside code blocks.

Also, the list indentation/dedentation is a great piece of UX.

**Comment by bmgxyz** [comment]
> I was thinking `\t` for inside inside code blocks.

Hmm, I suppose it would be nice to be able to use `\t` in code blocks. It looks like pressing `Tab` in the editor, both inside and outside of a code block, produces a single space. That's not great, but it's also not bad. Maybe in the future we can figure out how we want to improve this little piece, if at all.

I've just pushed a commit to fix the save prompting bug. At least, I think I've fixed it. Maybe give it a look and a try just to be sure I'm covering all of the applicable cases?

If everything looks acceptable to you, I'll probably merge sometime tomorrow.

**Comment by loboyd** [comment]
Everything seems to be working on my end now.

**Pull request merged**
